[[main]]
  name = "GitHub"
  url = "https://github.com/thulasirajkomminar"
  weight = 10

[[social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/thulasirajkomminar"
  weight = 20

[[social]]
  name = "X"
  url = "https://x.com/tkomminar"
  weight = 30
